### ISSUE TITLE
Add Dropbox

### ISSUE THREAD

**Issue by pawelostr** [ThatGuySam/doesitarm#112]
**The official name of the app**
Dropbox

**Proposed App Status**
Native - no.
Apparently works through Rosetta 2 using beta build here: https://www.dropboxforum.com/t5/Dropbox-desktop-client-builds/Beta-Build-110-3-425/td-p/469550

**Related Issue Tracker Link or discussion**
https://www.dropboxforum.com/t5/Dropbox-installs-integrations/Apple-Silicon-Macs/td-p/454545/page/3
https://www.dropboxforum.com/t5/Dropbox-desktop-client-builds/Beta-Build-110-3-425/td-p/469550

**An Official App Download Link**
https://www.dropbox.com/install

**Additional context**

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I’ll see if I can get a confirmation on the Rosetta support

**Comment by pawelostr** [comment]
Fully functional as of version 110.4.458 (https://www.dropboxforum.com/t5/Dropbox-desktop-client-builds/Stable-Build-110-4-458/td-p/470551) under Rosetta 2. Source: me

**Comment by pawelostr** [comment]
> Fully functional as of version 110.4.458 (https://www.dropboxforum.com/t5/Dropbox-desktop-client-builds/Stable-Build-110-4-458/td-p/470551) under Rosetta 2. Source: me

<img width="1091" alt="Zrzut ekranu 2020-11-19 o 19 41 57" src="https://user-images.githubusercontent.com/26488603/99709476-85ecfe00-2a9f-11eb-8f69-76308369c87a.png">

**Comment by xsbookmydesk** [comment]
@pawelostr @ThatGuySam 
I just installed version ` 110.4.458`.  It is a version that was released in 2020.
All other versions of Dropbox do not support M1. 
Before the old beta I had the regular latest stable installed, which was "fully functional" as well. It just shows up as Intel and fails the M1 compatible test. 

So because an very old beta passes the status should still be "unsupported".
