### ISSUE TITLE
TablePlus

### ISSUE THREAD

**Issue by alphatr** [ThatGuySam/doesitarm#144]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**The official name of the app**
TablePlus

**Proposed App Status**
✅ Yes, fully supported

**Related Issue Tracker Link or discussion**
https://github.com/TablePlus/TablePlus/issues/2180

**An Official App Download Link**
https://t.co/vc52yGaFze?amp=1

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

We'll use this as the Download link so people know what they are downloading is actually from TablePlus: 
https://twitter.com/TablePlus/status/1327650704295489536

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.
