### ISSUE TITLE
Fork git client

### ISSUE THREAD

**Issue by MaxDesiatov** [ThatGuySam/doesitarm#166]
**The official name of the app**
[Fork](https://git-fork.com/).

**Proposed App Status**
✳️ Can run well enough via Rosetta or some other caveat

**Related Issue Tracker Link or discussion**
N/A

**An Official App Download Link**
https://git-fork.com/update/files/Fork.dmg

**Additional context**
Response from the developer:
> We will add the ARM support in the future updates.

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

For the Status we'll say: 
✳️ Yes, works via Rosetta 2

For the Tracker Link we can use the Release Notes page: 
https://git-fork.com/releasenotes

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by MaxDesiatov** [comment]
Added in https://github.com/ThatGuySam/doesitarm/pull/170

**Comment by Ikloo** [comment]
**Native support for Apple Silicon (M1)** from `2.1` version
