### ISSUE TITLE
openocd

### ISSUE THREAD

**Issue by MrThanlon** [ThatGuySam/doesitarm#202]
**The official name of the app**
openocd

**Proposed App Status**
Native - no idea.
Rosetta - no idea.

**Proposed App Category**
no category

**Related Issue Tracker Link or discussion**

**An Official App Download Link**
http://openocd.org or https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/open-ocd.rb via Homebrew.

**Additional context**

**Comment by ThatGuySam** [comment]
We can use Developer Tools for the category on this one

**Comment by moffpage** [comment]
<img width="475" alt="image" src="https://user-images.githubusercontent.com/33549573/123597927-c53db300-d815-11eb-85b4-eb9fcabc90ca.png">
idk how do I check if a certain package has native support, is this info enough?

**Comment by ThatGuySam** [comment]
@moffpage If homebrew considers it native that's good enough for us. 

We'll use the following status:
✅ Yes, Full Native Apple Silicon Support

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/openocd/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
