### ISSUE TITLE
KeePassX

### ISSUE THREAD

**Issue by xanekka** [ThatGuySam/doesitarm#234]

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by xanekka** [comment]
The official name of the app {KeePassXC}

Is there a supported build available on a public/release channel? {Yes}

Proposed App Status {Yes, works via Rosetta 2}

Proposed App Category {Productivity Tools}

An Official App Download Link {https://keepassxc.org/download/#mac}

<img width="852" alt="Screen Shot 2020-11-23 at 9 56 15 PM" src="https://user-images.githubusercontent.com/11390681/100041151-c10c6b80-2dd6-11eb-8d2c-becbb7856bbb.png">

**Comment by ThatGuySam** [comment]
This looks good to go. 

Let's use this issue page as a Source link

* [KeePassXC](https://keepassxc.org/download/#mac) - ✳️ Yes, works via Rosetta 2 - [Source](https://github.com/ThatGuySam/doesitarm/issues/234)

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/keepassxc/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by Marc66** [comment]
KeepassXC now runs natively on M1. A specific download is available since yesterday: https://keepassxc.org/download/#mac

**Comment by ThatGuySam** [comment]
Thanks, @Marc66! 

Update is live! 

https://doesitarm.com/app/keepassxc/
