### ISSUE TITLE
Beyond Compare 4

### ISSUE THREAD

**Issue by mikkoxutvu** [ThatGuySam/doesitarm#242]
**The official name of the app**
Beyond Compare 4

**Proposed App Status**
[Not verified] Yes, works via Rosetta 2
According to their Facebook page (https://www.facebook.com/ScooterSoftware/), quote:
```
Beyond Compare 4.3.7 is an Intel CPU application, but will run on ARM CPU (Apple M1) Macs via Rosetta 2 translation. An ARM CPU version is in development.
```

**Proposed App Category**
Developer Tools

**An Official App Download Link**
https://www.scootersoftware.com/download.php
(License required but with a 30-day-evaluation.)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

That's plenty of verification. 

Status: ✳️ Yes, works via Rosetta 2

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.
