### ISSUE TITLE
 Eternal Storms Software (Yoink, ScreenFloat, Transloader, Glimpses, flickery, SiriMote)

### ISSUE THREAD

**Issue by KovalevArtem** [ThatGuySam/doesitarm#277]
**The official name of the app**
Yoink
ScreenFloat
Transloader
Glimpses
flickery
SiriMote

**Proposed App Status**
Yes

**Additional context**
![image](https://user-images.githubusercontent.com/36500228/99849264-4ea84b00-2b8c-11eb-85db-770a3f5a46f7.png)
https://blog.eternalstorms.at/2020/11/09/app-update-galore/

**Comment by ThatGuySam** [comment]
Status: ✅ Yes, full native support as of ${Version Number}

These will all go under Productivity Tools. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
Apps are now live on the site! 

Feel free to browse through the other issues to help with missing info on other apps.
