### ISSUE TITLE
MAMP

### ISSUE THREAD

**Issue by Kupodivu** [ThatGuySam/doesitarm#309]
**The official name of the app**
MAMP

**Proposed App Status**
No current status

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**
https://mampsupportforum.com/forums/categories/general-forum/apple-silicon-m1

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

Looks like we'll need a screenshot to verify support. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an Activity Monitor example on #176

**Comment by NicolasSy** [comment]
<img width="1072" alt="Capture d’écran 2020-11-25 à 11 43 57" src="https://user-images.githubusercontent.com/6407613/100217264-8f4cef00-2f13-11eb-8a15-2460d2132816.png">
It works via Rosetta 2.

App, server and database work, I can run a WordPress installation without any problem.

**Comment by ThatGuySam** [comment]
Fantastic!!

* [MAMP](https://www.mamp.info/en/mamp/mac/) - ✳️ Yes, works via Rosetta 2 - [Source](https://github.com/ThatGuySam/doesitarm/issues/309)

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/mamp/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
