### ISSUE TITLE
LaunchBar

### ISSUE THREAD

**Issue by LASER-Yi** [ThatGuySam/doesitarm#320]
**The official name of the app**
LaunchBar

**Is there a supported build available on a public/release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity

**Related Issue Tracker Link or discussion**
Nope, But I tested on my own machine

**An Official App Download Link**
https://www.obdev.at/downloads/launchbar/LaunchBar-6.13.1.dmg

**Screenshot with Activity Monitor(if self reporting)**
{As screenshot with Activity Monitor open showing the App's architecture type}
<img width="556" alt="image" src="https://user-images.githubusercontent.com/23134797/100169822-48ed9500-2eff-11eb-82cb-66b9a1cab893.png">

**Comment by ThatGuySam** [comment]
Thanks for App Request! 

We'll use the download page link so people know what they are downloading 
https://www.obdev.at/products/launchbar/download.html

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/launchbar

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
