### ISSUE TITLE
Tumult Hype

### ISSUE THREAD

**Issue by jmfd** [ThatGuySam/doesitarm#322]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**The official name of the app**
Tumult Hype

**Is there a supported build available on a public/release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Video and Motion Tools

**Related Issue Tracker Link or discussion**
Post: https://blog.tumult.com/2020/11/23/introducing-tumult-hype-v4-1-with-apple-silicon-and-big-sur-compatibility/

**An Official App Download Link**
https://tumult.com/hype/download/

**Screenshot with Activity Monitor(if self reporting)**
<img width="699" alt="Screen Shot 2020-11-24 at 7 34 48 PM" src="https://user-images.githubusercontent.com/489327/100180032-2ec69f00-2e8c-11eb-91ab-e68a49324993.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

We'll use the download page for the link so people know they are downloading
https://tumult.com/hype/

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by jmfd** [comment]
Thanks, I've added a pull request here:
https://github.com/ThatGuySam/doesitarm/pull/323

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/tumult-hype/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by jmfd** [comment]
Awesome - thanks!
