### ISSUE TITLE
Paragon NTFS for Mac

### ISSUE THREAD

**Issue by istvan60** [ThatGuySam/doesitarm#354]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**The official name of the app**
Paragon NTFS for Mac

**Is there a supported build available on a public/release channel?**
{Yes}
https://www.paragon-software.com/home/ntfs-mac/

**Proposed App Status**
Works on Apple Silicon natively

**Proposed App Category**
Productivity tools

**An Official App Download Page**
https://dl.paragon-software.com/beta/NTFS_for_Mac-15.8.84_Apple_Silicon.dmg

**Additional context**
Although the developer states it works, sbdy should try it out.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

If the developer is taking on the responsibility of claiming full support that plenty good enough for me. 

If we get reports that there are errors we'll update the status. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/paragon-ntfs/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
