### ISSUE TITLE
Lunar.fyi

### ISSUE THREAD

**Issue by jerots** [ThatGuySam/doesitarm#357]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**The official name of the app**
Lunar (https://lunar.fyi/)

**Is there a supported build available on a public/release channel?**
No

**Proposed App Status**
{What's the current app status based off of current discussion or testing
You can check the different statused here: 🚫 No, not yet supported only works on Intel-based Macs}

**Proposed App Category**
Utilities

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

We can use these as the Tracker links
https://github.com/alin23/Lunar/issues/210
https://github.com/alin23/Lunar/issues/215

We can go ahead and add this to the list. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/lunar-for-mac/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by alin23** [comment]
Lunar 4 has been released and it now has support for M1 Macs: https://lunar.fyi/#m1

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/lunar-for-mac/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by alin23** [comment]
Awesome, thanks! I'll look around and try to contribute ^_^

**Comment by jerots** [comment]
@ThatGuySam thank you!
