### ISSUE TITLE
eqMac

### ISSUE THREAD

**Issue by KovalevArtem** [ThatGuySam/doesitarm#362]
**The official name of the app**
eqMac

**Is there a supported build available on a public/release channel?**
Yes

**Proposed App Status**
?

**Proposed App Category**
Music and Audio Tools

**Related Issue Tracker Link or discussion**
https://github.com/bitgapp/eqMac/issues/413

**An Official App Download Page**
https://eqmac.app/

**Comment by ThatGuySam** [comment]
Looks like they've tested it on that issue. 

Status: ✳️ Yes, works via Rosetta 2 as of v0.3.7

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/eqmac/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
