### ISSUE TITLE
PS Remote Play

### ISSUE THREAD

**Issue by mahenzon** [ThatGuySam/doesitarm#441]
**The official name of the app**
PS Remote Play

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
:large_orange_diamond: Unknown, more info needed

**Proposed App Category**
Entertainment and Media Apps

**Related Issue Tracker Link or discussion**
https://remoteplay.dl.playstation.net/remoteplay/lang/en/index.html

**An Official App Download Page**
https://remoteplay.dl.playstation.net/remoteplay/lang/en/ps5_mac.html

**Additional context**
Big Sur is not even in the supported OS list

(Haven't tried it myself)

**Comment by ThatGuySam** [comment]
App is live on the list! 

https://doesitarm.com/app/ps-remote-play/

The next step is getting a screenshot. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by lawsonculver** [comment]
It works great!  I've used it to connect to the PS5 and played for a few hours total.

<img width="1353" alt="Screen Shot 2020-12-18 at 1 32 52 PM" src="https://user-images.githubusercontent.com/5569308/102654090-955e7600-4135-11eb-94b7-7780eb9cc8fc.png">

**Comment by lawsonculver** [comment]
It works great! I've used it to connect to the PS5 and played for a few hours total.

<img width="1353" alt="Screen Shot 2020-12-18 at 1 32 52 PM" src="https://user-images.githubusercontent.com/5569308/102654298-eff7d200-4135-11eb-880c-355bb22928d4.png">

**Comment by ThatGuySam** [comment]
@aardWolf64 Thanks for the screenshot! 

Update is now live on the site: https://doesitarm.com/app/ps-remote-play/

**Comment by codelerk** [comment]
![Screen Shot 2022-01-31 at 8 38 42 AM](https://user-images.githubusercontent.com/24785684/151803595-b97c43c7-9809-4100-b9b7-2ddb200eb707.png)

PS Remote play now runs on apple m1 natively.

**Comment by dalDevelo** [comment]
v4.5 of this application is not ARM native.I am still prompted to install Rosetta 2 when attempting to install PS Remote Play v4.5.

If files that indicate ARM compatibility are included in the app package, then this prompt for a Rosetta 2 install may be due to the installation package builder Sony uses requiring an update to include universal installer flags to be set. The installer may simply be assuming that Rosetta is needed because it is lacking a host architecture setting.

I just experienced this with another application and notified the Dev, who fixed it immediately by updating their install builder tool. I will notify Sony, but I think the main site needs to be updated to reflect the situation with the PS Remote Play app requesting Rosetta 2 as installation requirement.
