### ISSUE TITLE
REAPER

### ISSUE THREAD

**Issue by Kurville** [ThatGuySam/doesitarm#481]
**The official name of the app**
REAPER

**Is there a supported version available on a stable release channel?**
Yes (beta)

**Proposed App Status**
Full Native Support

**Proposed App Category**
Audio (Music)

**Related Issue Tracker Link or discussion**
https://forum.cockos.com/showthread.php?t=245263

**An Official App Download Page**
https://www.reaper.fm/download.php

**Full Screenshot with the App and Activity Monitor**

![reaper](https://user-images.githubusercontent.com/29205070/103934310-c3aaf200-50f2-11eb-9512-2af45a403b24.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Next, we'll need someone with an M1 to provide a screenshot. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by Kurville** [comment]
Updated with screenshot.

Le 2021-01-07 13:10, « Sam Carlton » a écrit :


Thanks for the App Request!

Next, we'll need someone with an M1 to provide a screenshot.

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version.

You can find an example on #358<https://github.com/ThatGuySam/doesitarm/issues/358>

**Comment by ThatGuySam** [comment]
It looks like there a note on the download page: 

> For maximum Intel plug-in compatibility, users with M1-powered Macs should use the Intel (10.15+) version rather than the native ARM64 beta version.

For the status, we'll put: ✳️ Yes, works via Rosetta 2 with native support in beta

Once the Native version is promoted to an official release leave an update on this issue

We can add it to the list with this. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/reaper/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
