### ISSUE TITLE
OpenJDK Azul builds

### ISSUE THREAD

**Issue by flying-sausages** [ThatGuySam/doesitarm#501]
Replace the text inside the {}'s with your own. 

For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/358

**The official name of the app**
{OpenJDK}

**Is there a supported version available on a stable release channel?**
{Yes}

**Proposed New App Status**
{✅ Yes, Full Native Apple Silicon Support}

**Related Issue Tracker Link or discussion**
{This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes.}

**An Official App Download Page**
{https://www.azul.com/downloads/zulu-community/?os=macos&architecture=arm-64-bit&package=jdk}

**Additional context**
{Azul Builds available for version 8, 11, 13 and 15}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{<img width="1531" alt="afbeelding" src="https://user-images.githubusercontent.com/23618693/103525953-58f28000-4e80-11eb-9d6f-b17c7e4b0d96.png">}

**Comment by ThatGuySam** [comment]
@flying-sausages How do these Azul Builds differ from what you find on https://openjdk.java.net/install/

**Comment by flying-sausages** [comment]
>  {Azul Builds available for version 8, 11, 13 and 15}

**Comment by flying-sausages** [comment]
Also, not sure I'm looking in the wrong place, but the site you linked does not provide AS builds for JDK 15 https://jdk.java.net/15/

**Comment by ThatGuySam** [comment]
I'm trying to find signalers that would show that the version that is generally considered official is supported. 

One example is that Homebrew links to java.net for their openjdk page: https://formulae.brew.sh/formula/openjdk

One scenario I'm trying to prevent is that we say "OpenJDK is supported natively on v8, 11, 13, 15" and then a developer buys an Apple SIlicon computer only to realize that only Zulu OpenJDK is native and in order for them to get it working on the new computer they have to rewrite their own app because it's built on the Oracle OpenJDK. 

Although it's probably impossible to fully summarize the situation in a few words, the goal is to provide the least misleading verbiage possible. 

Also, let me know if I'm understanding the Java ecosystem correctly.

**Comment by flying-sausages** [comment]
> a developer buys an Apple SIlicon computer only to realize that only Zulu OpenJDK is native and in order for them to get it working on the new computer they have to rewrite their own app because it's built on the Oracle OpenJDK

the application is OpenJDK, not JDK. From what I understand, the builds of OpenJDK are essentially interchangeable. Oracle's JDK to OpenJDK can be a transition, but OpenJDK itself should not pose any issues when moving between AdoptOpenJDK Builds and Azul's Open JDK Builds.

I haven't read this thoroughly but it seems to sum this up quite well. Even with Oracle to Azul, they're essentially drop-in. https://devexperts.com/blog/oracle-jdk-vs-openjdk-builds-comparison/

I'm gonna do

**Comment by ThatGuySam** [comment]
Alright, I've updated the listing to say: 
✅ Yes, Full Native Apple Silicon Support via Azul Zulu Builds

https://doesitarm.com/app/openjdk/

**Comment by flying-sausages** [comment]
Awesome, thanks! I'll close the issue now, I'll see if I can keep an eye on any java discussion for the future in case this comes up. If you notice something first, please link them from here if it's called in question :)
