### ISSUE TITLE
Netease Music

### ISSUE THREAD

**Issue by TonyAble** [ThatGuySam/doesitarm#528]
**The official name of the app**
Netease Music

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Music

**An Official App Download Page**
https://music.163.com/#/download

**Additional context**
A music streaming service from China.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="510" alt="Screen Shot 2021-01-19 at 22 55 41" src="https://user-images.githubusercontent.com/13818376/105051219-860e7780-5aa9-11eb-8735-bceb3f80d5d3.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

We'll add this under Entertainment and Media Apps since we already have Spotify there. 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/netease-music/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
