### ISSUE TITLE
DisplayLink Manager

### ISSUE THREAD

**Issue by dvdsnchzIT** [ThatGuySam/doesitarm#567]
**The official name of the app**
DisplayLink Manager

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
https://s3.eu-west-1.amazonaws.com/assets.displaylink.com/live/downloads/release-notes/f1698_DisplayLink+Manager+Graphics+Connectivity+1.3-Release+Notes.txt

**An Official App Download Page**
https://www.displaylink.com/downloads/macos

**Additional context**
No

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

For Status: 
✅ Yes, Full Native Apple Silicon Support as of v1.3

This is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/displaylink-manager/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
