### ISSUE TITLE
XMind now support M1 fully natively

### ISSUE THREAD

**Issue by YIMINGMA** [ThatGuySam/doesitarm#714]
**The official name of the app**
XMind

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
Full M1 Native Support

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Links or discussion**
Here is the official [GitHub Repo](https://github.com/xmindltd/xmind) of XMind, but it does NOT contain any info about M1 support.

**An Official App Download Page**
On [Mac App Store](https://apps.apple.com/us/app/xmind-mind-map/id1286983622)

**Additional context**
None.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
(Sorry it's in Chinese.)
<img width="1219" alt="iShot2021-06-29 09 23 36" src="https://user-images.githubusercontent.com/45311510/123763764-06889e00-d8bc-11eb-81c5-5af57252f4c2.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

We'll use the following status:
✅ Yes, Full Native Apple Silicon Support

We'll use the following category: 
Productivity Tools


Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/xmind/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
