### ISSUE TITLE
Mutagen

### ISSUE THREAD

**Issue by drpayyne** [ThatGuySam/doesitarm#762]
**The official name of the app**
[Mutagen](https://github.com/mutagen-io/mutagen)

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Yes, works via Translation or Virtualization

**Proposed App Category**
Developer Tools

**Related Issue Tracker Links or discussion**
https://github.com/mutagen-io/mutagen/releases

**An Official App Download Page**
https://mutagen.io/documentation/introduction/installation

**Additional context**
This is currently under development and in beta. Native Apple Silicon support has been available since v0.12.0-beta3. Native support should be available very soon in the next stable release.

**Comment by drpayyne** [comment]
CC: @xenoscopic

**Comment by xenoscopic** [comment]
Mutagen's v0.11.x releases should work under Rosetta 2 locally (i.e. for hosting the Mutagen daemon, using the `mutagen` command, and for hosting local synchronization/forwarding endpoints).  They won't work when targeting remote Apple Silicon endpoints because the v0.11.x architecture detection doesn't recognize Apple Silicon (though one can still manually copy the `darwin`/`amd64` `mutagen-agent` binary to the remote system if and have it run under Rosetta 2, if desired).

The v0.12.x releases are significantly better in their support for Apple Silicon.

**Comment by drpayyne** [comment]
Thanks @xenoscopic! 

> The v0.12.x releases are significantly better in their support for Apple Silicon.

Just to clarify, does this mean "native support" without Rosetta?

**Comment by xenoscopic** [comment]
Correct, they're natively compiled for Apple Silicon and also correctly detect Apple Silicon remotes.  Thanks for asking!

**Comment by drpayyne** [comment]
Thank you so much for your work, @xenoscopic 🚀

**Comment by ThatGuySam** [comment]
Status: 
✳️ Yes, works via Rosetta 2 Translation 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by drpayyne** [comment]
PR added at https://github.com/ThatGuySam/doesitarm/pull/767

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/mutagen/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by u-maxx** [comment]
Hello @drpayyne, thanks for adding Mutagen to the list, but since v0.12.0 it has native support of the Apple Silicon - https://github.com/mutagen-io/mutagen/releases/tag/v0.12.0 I am going to create a new PR to update the info here.

**Comment by u-maxx** [comment]
@ThatGuySam I have created new PR with the updated info - https://github.com/ThatGuySam/doesitarm/pull/811

Thank you for the hard work on the Mutagen project @xenoscopic!
