### ISSUE TITLE
SideFX Houdini 18.5

### ISSUE THREAD

**Issue by Noirai** [ThatGuySam/doesitarm#82]
SideFX Houdini (Apprentice) 18.5

Official App Download Link
https://www.sidefx.com/download/

Discussion / Tracker:
https://www.sidefx.com/forum/topic/74322/?page=1#post-314051

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by Noirai** [comment]
Videos of Houdini 18.5 Apprentice running on M1 with Rosetta 2:
https://www.youtube.com/watch?v=vhRmuJ8yheM&feature=youtu.be
https://www.youtube.com/watch?v=nAnZDBiR8Z0&feature=youtu.be

Discussion:
https://www.reddit.com/r/Houdini/comments/jzg1wj/houdini_running_on_apple_silicon_m1_macs_demo/

**Comment by ThatGuySam** [comment]
Status: ✳️ Yes, works via Rosetta 2

Let’s use the Reddit post as the source link



Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.
