### ISSUE TITLE
Transmit 5 seems not supporting native ARM. (Dec 5th)

### ISSUE THREAD

**Issue by indicator0** [ThatGuySam/doesitarm#838]
Replace each second line your own text. 

**The official name of the app**
Transmit 5

**Is there a supported version available on a stable release channel?**
Yes (via Rosetta 2)

**Proposed New App Status**
Doeesitarm website shows that v5.7 runs natively on Apple Silicon, but v5.8.2 is still x86_64 version.

**Related Issue Tracker Links or discussion**
None

**An Official App Download Page**
Mac App Store or https://www.panic.com/transmit/

**Additional context**
Please check it if you have this app.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

<img width="647" alt="Screenshot 2021-12-05 at 16 24 03" src="https://user-images.githubusercontent.com/39152296/144739231-2c7e9799-d477-4428-bd92-4b11dde6626e.png">

**Comment by ThatGuySam** [comment]
There are 3 types of App Bundles in the context of Apple Silicon: Intel, Apple, and Universal. 

**Intel** is the older App Bundles that we've used in the past and may work on Apple Silicon via Rosetta 2 Translation. 

**Apple** is specifically built for Apple Silicon devices and will not run on Intel Macs. 

**Universal** contains both the Intel and Apple bundle data and will run on either but is usually about double the size. 

Sometimes software developers will continue to ship Intel-only App Bundles instead of Universal to make downloads faster and save on Disk Space. 

I imagine the App Store has an option to provide Architecture specific versions instead of only the Universal version.

**Comment by indicator0** [comment]
I wrongly downloaded thee x64 only version, now it is natively ARM!
